### ISSUE TITLE
Use a 64-bit value for pi

### ISSUE THREAD

**Issue by axch** [edoddridge/MIM#10]
No reason to lose accuracy for a dozen source code characters.

From http://stackoverflow.com/questions/507819/pi-and-accuracy-of-a-floating-point-number, 3.1415926535897932384 should be sufficient.

I am loath to just do this myself until more of the testing is in place.  Ideally, from my point of view, I would see accuracy improve (slightly) from making the change.  @edoddridge, if you feel differently, don't let me stop you from just editing the file and closing this ticket.

**Comment by edoddridge** [comment]
Fair point. The value for pi is only used in three places:
* To calculate the spectral radius of the grid for the matrix inversion algorithm.  The spectral radius is used as an approximate guide to help the algorithm converge faster. It's not a high accuracy usage. https://github.com/edoddridge/MIM/blob/master/MIM.f90#L333
* To calculate the sinusoidally varying wind component - if that option is being used.
https://github.com/edoddridge/MIM/blob/master/MIM.f90#L527 & 
https://github.com/edoddridge/MIM/blob/master/MIM.f90#L530

Given that the value isn't used directly in the computation, I'm happy just updating it.

**Comment by axch** [comment]
FYI, if you write `Closes #10` or `Fixes #10` in the commit log, Github will close the issue automatically.  Didn't know whether you knew that.  https://help.github.com/articles/closing-issues-via-commit-messages/
