### ISSUE TITLE
Provide a way for the user to change the grid size without recompiling

### ISSUE THREAD

**Issue by axch** [edoddridge/MIM#12]
Does Fortran make this difficult by defaulting to fixed-size arrays?

I can imagine several ways to achieve this:
- Find the dynamically-sized arrays feature (it must exist) and use it.  Are there any disadvantages to this?
- Replace the compile-time constant sizes with compile-time constant maximum sizes, and only operate on the subsection of the array that the user actually asked for.  This wastes some amount of memory, but presumably not enough to be a problem; and requires recompilation to change the maximum, but that's presumably less onerous than having to recompile to change the resolution at all.

Regardless, we should make sure that we still have bounds checks for indexing those arrays, to the extent this is possible.

**Comment by edoddridge** [comment]
This would be a good feature.

The Fortran allocatable arrays feature (described here: http://www.pcc.qub.ac.uk/tec/courses/f90/stu-notes/F90_notesMIF_11.html) would let us do this. I think the only downside is the possibility of memory leaks. 

I'm not sure about static arrays with some maximum size. Potential changes in grid size are likely to be very large - factors of ten or more.

**Comment by axch** [comment]
How does the program's runtime and memory use scale with the grid size?  That may affect this decision, and in any case we should know, because we should document it for the users.  (Notably, what are the dimensions of that matrix that needs inverting?)

**Comment by edoddridge** [comment]
The memory usage scales quadratically in `nx` or `ny` - so doubling the grid resolution quadruples the memory requirement. The run time scales as the cube, since the time step has to be halved to maintain stability.

For the n-layer physics the performance may be slightly worse since the number of iterations for the matrix inversion to converge also scales with the grid. The size of the matrix that needs inverting is the size of the grid, so `nx` by `ny`.

**Comment by axch** [comment]
Just to make sure I understand: memory use is O(nx ny layers), reduced-gravity run time is O(nx ny layers nt), (where nt should be O(nx + ny) to be stable), and the additional matrix being inverted for n-layer physics has O(nx ny) _elements_ (not rows, which would presumably not fit into O(nx ny) memory)?

**Comment by edoddridge** [comment]
I'd say that nt should be O(max(nx, ny)), rather than the sum. 

Otherwise, yes, that's all correct.

**Comment by axch** [comment]
Well, O(max(x, y)) = O(x + y), because those two quantities cannot differ by more than a factor of two (assuming x, y > 0).
