### ISSUE TITLE
Choose a code style and make the code conform to it

### ISSUE THREAD

**Issue by axch** [edoddridge/MIM#17]
At minimum, we should address the following points (which have already disoriented me):
- [x] Choose code indentation discipline.  Traditionally, all statements within a given block are indented relative to the block header by a constant amount (I prefer two spaces, but this program seems to be going with 4, which is also the strong convention in Python), and block headers and footers are at the same indentation level, determined by the enclosing block.  Top level blocks are traditionally completely not indented.  I mention this because https://github.com/edoddridge/MIM/blob/9adaded177146e50a9cea68b64bd5080cf13939b/MIM.f90#L700 and https://github.com/edoddridge/MIM/blob/9adaded177146e50a9cea68b64bd5080cf13939b/MIM.f90#L795, for example, appear to deviate.  Do Fortran conventions differ significantly?  In particular, I propose adopting what is called "free-form", unless there is a reason to do otherwise.  My inclination for a specific convention is to do whatever the automatic indentation in Emacs' built-in F90 mode does, once configured to the desired subblock offset (i.e., 2 or 4 spaces).
- [ ] Enforce that choice.
- [x] Choose comment indentation discipline.  In languages other than Fortran, it is traditional for the comment character (`!`, in this case) beginning a line comment to be indented to the same level as the surrounding statements, and for the content of the comment to be separated therefrom by a space.  Shall we adopt this, in spite of the prevalence of beginning-of-line comment marks in the code?  Or is a different convention preferable?
- [ ] Enforce that choice.
- [x] Choose a maximum line length.  80 characters (including the indentation, if any) is traditional.
- [ ] Enforce that choice by naming temporaries (preferred) or using the line continuation syntax (where necessary).

**Comment by axch** [comment]
We should make the decisions sooner rather than later; but I am loath to actually enforce them until the regrid branch is merged (or abandoned), and until I have a refactoring test suite to catch any mistakes I may, in my non-knowledge of Fortran, make while changing what I think is just style.

**Comment by edoddridge** [comment]
I agree with all of this, and am happy to go with the indentation suggested by Emacs defaults.

The prevalence of comment characters at the beginning of lines is a hangover from the F77 convention in which comments where signified by a 'c' in the first column. There is no reason to keep them like that.

**Comment by axch** [comment]
OK, awesome.  I will try to find time this weekend to implement this, if I can.  I prefer 2-space indentation (even in Python, contrary to the Python community's strong preference for 4).  Do you care?  The extant Fortran code is mostly indented 4 spaces; do you want to keep it that way?  (We also don't have to indent Python and Fortran the same way.)

**Comment by axch** [comment]
Hm.  I don't seem to have permissions to assign this issue to myself.  Can you do that?  Also Issue #6, which I want to do first.

**Comment by edoddridge** [comment]
I've assigned this to you, and also added you as a collaborator, so you should be able to do that yourself in the future.

I'm happy with 2 space indentation for Fortran - the current tendency towards 4 space is not especially intentional. I'd prefer to stick with 4 space indents for Python.

**Comment by axch** [comment]
Sounds good.  The 4-space convention in Python is too strong to resist, little though I may like it.
