### ISSUE TITLE
Generalize sinusoidal and stochastic wind to a time series of wind amplitude?

### ISSUE THREAD

**Issue by axch** [edoddridge/MIM#21]
Accepting and storing such a time series in memory would have a negligible cost on performance, and produce several benefits:
- Fully custom patterns of time variation of the wind (how important is this in practice?)
- Opportunity to eliminate that code from Fortran, making it that much easier to validate, and to trust by inspection
  - In particular, the core of MIM would then become completely deterministic, obviating Issues #8 and #9
- Simpler configuration of the core
- No pressure to implement new wind patterns (if any others are used in practice), at least not in Fortran

While one is at it, one could also permit time-varying rotation of the wind (by a uniform angle over the entire surface), or go wild and allow the two wind components to be sheared by an arbitrary time-dependent affine transformation of the base wind and the coordinates:
```
(true_wind_x, true_wind_y)(t, x, y)
  = M(t) * (1, base_wind_x(x, y), base_wind_y(x, y), x, y)
```
where M(t) is a 2x5-matrix-valued time series specified as input.

I presume that inviting the user to supply the entire wind forcing as an arbitrary time-varying field is a bit much, as this will call for input data that is only about O(num layers) times smaller than the output.

Note: Ease of use for the particular cases of sinusoidal and stochastic wind can be retained by shipping helpers in the Python (and Matlab) utility packages that compute the wind time series in question from the current parameterization of the sinusoidal and stochastic wind features.

**Comment by edoddridge** [comment]
This would be good. Not only for the reasons you list but also to reduce clutter in the parameters.in file.

Specifying fully custom patterns of time varying intensities for the wind is something that has been done in the literature, and as you say the array is not going to be a memory issue.

Specifying a completely arbitrary wind field for each time step would be cumbersome. Many models get around this by taking a number of fields with associated timestamps and interpolating between them. Often these fields represent monthly averages and the model simply uses them in a repeating cycle. This may be worth exploring in the future.

I think the advantages of taking this functionality out of MIM and putting in the front end are worth it. However, I'm not (yet) convinced about the affine transformation.

**Comment by axch** [comment]
Ah, key-frame animation.  Good idea.  Definitely not a "minimum viable product" feature, though :)

The affine transformation is also more of an idea for the future, if at all.

But I am hearing a decision to replace the sinusoidal and stochastic wind features with an input time series to the Fortran core.  Sounds good.
