### ISSUE TITLE
Investigate and fix memory corruption crash (!) unmasked by compiling with -O1

### ISSUE THREAD

**Issue by axch** [edoddridge/MIM#28]
If I change `output_preservation_test.py` to compile the MIM core with `-O1` or `-O2` rather than `-Ofast`, two undesirable things happen:
- All three of the n-layer simulations crash with a memory corruption error (`*** Error in 'MIM': double free or corruption (!prev): 0x00000000007c8a90 ***`).
- Two of the reduced gravity simulations give outputs that disagree with the known good ones.

The latter problem is Issue #29.  It is presumably due to `gfortran -Ofast` taking liberties with the IEEE 64-bit floating point standard, but it would be nice to check that (e.g., by an application of the first solution proposed for Issue #27).

The former problem seriously troubles me.  What in the world could `-Ofast` be doing that would mask a memory corruption problem that `-O1` finds?  Regardless of the answer to that question, I guess it's time to bust out `gdb` (and the Internet's copious guidance on how to use it on Fortran programs).

**Comment by axch** [comment]
One of the crash outputs contained the following snippet:
```
Program received signal SIGABRT: Process abort signal.

Backtrace for this error:
#0  0x7F40D7436777
#1  0x7F40D7436D7E
#2  0x7F40D6D88CAF
#3  0x7F40D6D88C37
#4  0x7F40D6D8C027
#5  0x7F40D6DC52A3
#6  0x7F40D6DD155D
#7  0x408464 in evaluate_b_iso_
#8  0x40D4D7 in MAIN__ at MIM.f90:?
```

Could this be a problem of reading from or writing to unallocated memory, by subscripting off the end of an array?  Indeed, the statements https://github.com/edoddridge/MIM/blob/master/MIM.f90#L855 and https://github.com/edoddridge/MIM/blob/master/MIM.f90#L862 suggest that the array `z`, declared at https://github.com/edoddridge/MIM/blob/master/MIM.f90#L842, should have the same size as `h` and `M`, but it does not.  Changing the dimensions of `z` to `double precision z(0:nx+1, 0:ny+1, layers)` eliminates the crash on my system.

The decision now is whether to
- go through the exercise of finding this problem with a repeatable process (i.e., practice gdb), and/or
- set up the test suite to fail because of it (i.e., practice test-driven development), or just
- fix it and pretend it was just a bad dream?

Considerations:
- Shipping code that interacts with memory it didn't allocate is no bad dream, but a full-scale nightmare -- [ask Cloudflare!](https://en.wikipedia.org/wiki/Cloudbleed)
- The fix (like pretty much any code change) would conflict with PR #25, so if that's a quick merge, we should just merge it first.

**Comment by edoddridge** [comment]
That is just a straight up bug that I, presumably, introduced with the `regrid` branch. The array `z` should definitely have the same shape as `h` and `M`.

It looks like Valgrind does work with Fortran. Seems like it would a sensible addition to the test suite.
