### ISSUE TITLE
Compiling MIM with -fcheck=all detects an array bounds error

### ISSUE THREAD

**Issue by axch** [edoddridge/MIM#50]
To wit:
```
At line 588 of file MIM.f90
Fortran runtime error: Index '0' of dimension 1 of array 'dvdt_bt' below lower bound of 1
```

Widening the lower bound to 0 removes the warning (and has no visible effect on output), but now I am confused: `dvdt_bt` and `dudt_bt` seem to have asymmetric sizes, and also seem to be bigger than needed.  To wit, looking at that the do loops where they are used, I would think that declaring them as `dudt_bt(nx, 0:ny)` and `dvdt_bt(0:nx, ny)` would suffice.  (Running the test suite with `-fcheck=all` agrees.)

@edoddridge Is this just a typo or paste-o in the bounds?  Or is something more subtle going on here?

General comments, in case this seems like a triviality:
- Accessing memory out of allocated bounds is always very bad, even if it's a "small" amount and doesn't seem to change the answers during testing.
- Declaring arrays larger than they need to be has negligible performance cost, but is worth documenting or correcting because it can confuse a reader (Why is that extra slot there?  Is it being used in some subtle way I don't understand?).

**Comment by edoddridge** [comment]
I understand the issues with accessing memory that is out of the allocated region. 

This is actually an issue with the loop bounds. The domain that the model actually solves goes from:
* `i` = 1 to `i` = `nx`; and 
* `j` = 1 to `j` = `ny`
the halo of points around this domain are intended to be used when periodic boundary conditions are implemented. Thus, these loops should go from 1 to `nx` and 1 to `ny`. 

If you look at the `wrap_fields` [subroutines](https://github.com/edoddridge/MIM/blob/master/MIM.f90#L1622) you'll see that the value at `i` = 0 is set to the value at `i` = `nx`, and the value at `i` = `nx+1` is set to the value at `i` = 1. This means there's no point wasting cycles having the loops start at 0.

After the two loops adding the barotropic velocity tendencies to the other tendencies there should be some calls to the `wrap_fields` subroutine, say around line [593](https://github.com/edoddridge/MIM/blob/master/MIM.f90#L593).

I'll merge your pull requests and then deal with this.

**Comment by axch** [comment]
Actually, can you hold off on rearranging that for now?  I have a half-done PR for #12, which will introduce conflicts with any changes to array bounds.

**Comment by edoddridge** [comment]
Sure thing. I'll wait for that to come through.
