### ISSUE TITLE
Declare intent for all variables in subroutines

### ISSUE THREAD

**Issue by edoddridge** [edoddridge/MIM#54]
Declaring the [intent](https://en.wikibooks.org/wiki/Fortran/Fortran_procedures_and_functions#Intent) for variables in subroutines can apparently lead to optimisation gains, and will also help [clean up the coupling with Python](https://docs.scipy.org/doc/numpy-1.10.0/user/c-info.python-as-glue.html) if we go down that road.

**Comment by axch** [comment]
+1.  Somewhat annoying caveat: "no intent" is different from "intent (inout)", per section 5.1.2.3 of [the standard](http://j3-fortran.org/doc/standing/archive/007/97-007r2/pdf/97-007r2.pdf).  One example of the difference seems to be that an argument with "intent (in)" in procedure A may be passed to an argument with no declared intent in procedure B, but not to one declared "intent (inout)".  This means we can't necessarily declare a style of requiring all procedure arguments to have declared intents, though it's possible that we will be able to in this particular program.
