### ISSUE TITLE
Split the main program up into sensible subroutines

### ISSUE THREAD

**Issue by axch** [edoddridge/MIM#70]
Benefits:
- Increase comprehensibility by naming semantic parts, and by spelling out the means of communication between them (especially in light of the intent declarations called for by Issue #54).
- Reduce duplication of code by naming and reusing repeated chunks (like the state derivative computation), and gain comprehensibility and hackability thereby.
- Increase precision of procedure-wise profiling, per the complaint in Issue #48.
- Increase the number of easy attachment points for a hypothetical Python driver, per f2py.

**Comment by axch** [comment]
I've started working on this, and it causes a lot of code rearrangement, so we probably shouldn't do anything more to the core until this completes, on pain of merge conflicts.

**Comment by axch** [comment]
An unexpected beneficial consequence of this project: the time needed to compile the core has fallen drastically.  I'm guessing there's some kind of flow or alias analysis in the compiler whose runtime scales with the product of #variables by #statements in some function, or #variables squared, or some such.

**Comment by edoddridge** [comment]
That's a nice side effect!
